/*
- DO NOT edit this file.
- Simply copy the contents into a new file config/config.js
  and add your machine specifc configuration in that file
*/


module.exports = {

	mysql: {
		username: 'your-mysql-user-name',
		password: 'your-mysql-password',
		port: 3306 // or your mysql port
	},

	server: {
		port: 3000 // port on which the application would run
	}

};